### ISSUE TITLE
Use code coverage

### ISSUE THREAD

**Issue by davidsoderberg** [peridot-php/peridot-code-coverage-reporters#12]
Hi, I do not management to get it to report code coverage. Do I need to put any parameters in terminal on run?

**Comment by ezzatron** [comment]
Sorry I didn't see this earlier. I'm not sure if you're still having trouble, but you could take a look at [peridot-jumpstart's configuration](https://github.com/peridot-php/peridot-jumpstart/blob/master/peridot.php) to see how this library is used there. The minimum you need is:

```php
use Evenement\EventEmitterInterface;
use Peridot\Reporter\CodeCoverageReporters;

return function (EventEmitterInterface $emitter) {
    $coverage = new CodeCoverageReporters($emitter);
    $coverage->register();
};
```

In addition, you'll need a PHP runtime that supports coverage reporting. That is, you can either:

- Run your tests using phpdbg (e.g. `phpdbg -qrr vendor/bin/peridot`) (recommended)
- Run your tests using a version of PHP with xdebug enabled.

**Comment by davidsoderberg** [comment]
I wrote my one code coverage repoter for this instead :)

**Comment by shadowhand** [comment]
This issue should not be closed. The docs state nothing about using `phpdbg` and I just wasted 2 hours trying to figure out why coverage was not working. 😠

**Comment by ezzatron** [comment]
As I mentioned in #8, `phpdbg` is not a requirement of `peridot-code-coverage-reporters`, but actually [sebastianbergmann/php-code-coverage].

Off the top of my head, ways we could improve the experience here include:
- Updating the README and website with up-to-date installation instructions.
- Mention the requirement for a code coverage driver.
- Merge this repo with Peridot proper, implement a flag like `--no-coverage`, and complain when there is no coverage driver unless `--no-coverage` is used. This is what recent PHPUnit versions do.

[sebastianbergmann/php-code-coverage]: https://github.com/sebastianbergmann/php-code-coverage
