### ISSUE TITLE
Uncaught Error: Class 'Peridot\Reporter\CodeCoverageReporters' not found

### ISSUE THREAD

**Issue by Radiergummi** [peridot-php/peridot-code-coverage-reporters#16]
I'm a little confused by the other issues, and maybe I got it all wrong. But my impression was: Install the plugin, add the snippets from README to my peridot.php and run `peridot` with my xdebug-enabled PHP executable?  
As I'm doing this, I receive the following error:

    PHP Fatal error:  Uncaught Error: Class 'Peridot\Reporter\CodeCoverageReporters' not found in /Users/mo/PhpstormProjects/foundation/peridot.php:18
    Stack trace:
    #0 [internal function]: Peridot\Console\Environment->{closure}(Object(Evenement\EventEmitter))
    #1 /Users/mo/.composer/vendor/peridot-php/peridot/src/Console/Environment.php(119): call_user_func(Object(Closure), Object(Evenement\EventEmitter))
    #2 /Users/mo/.composer/vendor/peridot-php/peridot/src/Console/Environment.php(80): Peridot\Console\Environment->includeConfiguration('/Users/mo/Phpst...')
    #3 /Users/mo/.composer/vendor/peridot-php/peridot/src/Console/Environment.php(57): Peridot\Console\Environment->loadConfiguration('/Users/mo/Phpst...')
    #4 /Users/mo/.composer/vendor/peridot-php/peridot/src/Console/Application.php(211): Peridot\Console\Environment->load('/Users/mo/Phpst...')
    #5 /Users/mo/.composer/vendor/peridot-php/peridot/src/Console/Application.php(43): Peridot\Console\Application->validateConfiguration()
    #6 /Users/mo/.composer/vendor/peridot-php/peridot/ in /Users/mo/PhpstormProjects/foundation/peridot.php on line 18

Composer autoloading works flawlessly otherwise, I'm using Leo already and it's great. But I'd like to get code coverage reporting for my tests, so there seems to be something going seriously wrong here.

**Comment by Radiergummi** [comment]
Okay, I solved the issue by installing this package globally. A note in the readme on that would be valuable, tho.

**Comment by ezzatron** [comment]
Hi @Radiergummi, installing "globally" doesn't sound like a good solution here. Could you clarify what you mean by that?

Additionally, a while ago I had a go at re-writing the README in tandem with adding support for later versions of `php-code-coverage`. Could you take a look at [this branch](https://github.com/peridot-php/peridot-code-coverage-reporters/tree/phpcc-4-5) and let me know if the instructions make more sense, or work better for you?

**Comment by Radiergummi** [comment]
Hey @ezzatron, by globally I meant exactly that - `composer global require peridot-php/peridot-code-coverage-reporters`. I figured since Peridot is installed globally as well, I'd give it a try.  
The other branch looks great, I'll give it a try this afternoon.

Sorry to bug you with this - it's my first time testing a large scale application in PHP and I really appreciate your help 😊

**Comment by ezzatron** [comment]
Ah okay, that makes more sense, I didn't realise you were running Peridot itself globally. I would probably advise against that approach.

Most people tend to include the test runner (Peridot/PHPUnit/whatever) as a Composer dev dependency. This approach helps avoid maintenance issues when a new version of the test runner is released. It also means your CI server (if you have one) doesn't have to have Peridot pre-installed.

**Comment by ezzatron** [comment]
Forgot to mention, when installed "locally" peridot can be run from `vendor/bin/peridot` (`vendor/bin` is the standard Composer path for installed binaries).
